package com.disenio.entities.mascotas;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TamanioMascota generated by hbm2java
 */
@Entity
@Table(name="tamanio_mascota"
    ,catalog="patitas"
)
public class TamanioMascota  implements java.io.Serializable {


     private Integer idTamanio;
     private String descripcion;
     private char estado;
     private Set mascotaRescatadas = new HashSet(0);

    public TamanioMascota() {
    }

	
    public TamanioMascota(String descripcion, char estado) {
        this.descripcion = descripcion;
        this.estado = estado;
    }
    public TamanioMascota(String descripcion, char estado, Set mascotaRescatadas) {
       this.descripcion = descripcion;
       this.estado = estado;
       this.mascotaRescatadas = mascotaRescatadas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_TAMANIO", unique=true, nullable=false)
    public Integer getIdTamanio() {
        return this.idTamanio;
    }
    
    public void setIdTamanio(Integer idTamanio) {
        this.idTamanio = idTamanio;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="ESTADO", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tamanioMascota")
    public Set<MascotaRescatada> getMascotaRescatadas() {
        return this.mascotaRescatadas;
    }
    
    public void setMascotaRescatadas(Set mascotaRescatadas) {
        this.mascotaRescatadas = mascotaRescatadas;
    }




}


