package com.disenio.entities.mascotas;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoMascota generated by hbm2java
 */
@Entity
@Table(name="tipo_mascota"
    ,catalog="patitas"
)
public class TipoMascota  implements java.io.Serializable {


     private Integer idTipoMascota;
     private String nombre;
     private Set mascotaRescatadas = new HashSet(0);
     private Set mascotas = new HashSet(0);

    public TipoMascota() {
    }

	
    public TipoMascota(String nombre) {
        this.nombre = nombre;
    }
    public TipoMascota(String nombre, Set mascotaRescatadas, Set mascotas) {
       this.nombre = nombre;
       this.mascotaRescatadas = mascotaRescatadas;
       this.mascotas = mascotas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_TIPO_MASCOTA", unique=true, nullable=false)
    public Integer getIdTipoMascota() {
        return this.idTipoMascota;
    }
    
    public void setIdTipoMascota(Integer idTipoMascota) {
        this.idTipoMascota = idTipoMascota;
    }

    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoMascota")
    public Set<MascotaRescatada> getMascotaRescatadas() {
        return this.mascotaRescatadas;
    }
    
    public void setMascotaRescatadas(Set mascotaRescatadas) {
        this.mascotaRescatadas = mascotaRescatadas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoMascota")
    public Set<Mascota> getMascotas() {
        return this.mascotas;
    }
    
    public void setMascotas(Set mascotas) {
        this.mascotas = mascotas;
    }




}


