package com.disenio.entities.caracteristicas;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import com.disenio.entities.Views;
import com.disenio.entities.organizacion.Organizacion;
import com.fasterxml.jackson.annotation.JsonView;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Caracteristica generated by hbm2java
 */
@Entity
@Table(name = "caracteristica"
        , catalog = "patitas"
)
public class Caracteristica implements java.io.Serializable {

    @JsonView(Views.External.class)
    private Integer idCaracteristica;
    @JsonView(Views.External.class)
    private ComportamientoTipo comportamientoTipo;
    @JsonView(Views.External.class)
    private Organizacion organizacion;
    @JsonView(Views.External.class)
    private String descripcionFaq;
    @JsonView(Views.External.class)
    private Date fechaAlta;
    @JsonView(Views.External.class)
    private Date fechaUltimaModificacion;
    @JsonView(Views.External.class)
    private Date fechaBaja;
    @JsonView(Views.External.class)
    private char estado;
    @JsonView(Views.External.class)
    private List<CaracteristicaValor> caracteristicaValors;

    public Caracteristica() {
    }


    public Caracteristica(ComportamientoTipo comportamientoTipo, Organizacion organizacion, String descripcionFaq, Date fechaAlta, Date fechaUltimaModificacion, char estado) {
        this.comportamientoTipo = comportamientoTipo;
        this.organizacion = organizacion;
        this.descripcionFaq = descripcionFaq;
        this.fechaAlta = fechaAlta;
        this.fechaUltimaModificacion = fechaUltimaModificacion;
        this.estado = estado;
    }

   /* public Caracteristica(ComportamientoTipo comportamientoTipo, Organizacion organizacion, String descripcionFaq, Date fechaAlta, Date fechaUltimaModificacion, Date fechaBaja, char estado, List<CaracteristicaValor> caracteristicaValors) {
        this.comportamientoTipo = comportamientoTipo;
        this.organizacion = organizacion;
        this.descripcionFaq = descripcionFaq;
        this.fechaAlta = fechaAlta;
        this.fechaUltimaModificacion = fechaUltimaModificacion;
        this.fechaBaja = fechaBaja;
        this.estado = estado;
        this.caracteristicaValors = caracteristicaValors;
    }*/

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "ID_CARACTERISTICA", unique = true, nullable = false)
    public Integer getIdCaracteristica() {
        return this.idCaracteristica;
    }

    public void setIdCaracteristica(Integer idCaracteristica) {
        this.idCaracteristica = idCaracteristica;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_COMPORTAMIENTO_TIPO", nullable = false)
    public ComportamientoTipo getComportamientoTipo() {
        return this.comportamientoTipo;
    }

    public void setComportamientoTipo(ComportamientoTipo comportamientoTipo) {
        this.comportamientoTipo = comportamientoTipo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_ORGANIZACION", nullable = false)
    public Organizacion getOrganizacion() {
        return this.organizacion;
    }

    public void setOrganizacion(Organizacion organizacion) {
        this.organizacion = organizacion;
    }


    @Column(name = "DESCRIPCION_FAQ", nullable = false, length = 100)
    public String getDescripcionFaq() {
        return this.descripcionFaq;
    }

    public void setDescripcionFaq(String descripcionFaq) {
        this.descripcionFaq = descripcionFaq;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_ALTA", nullable = false, length = 0)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }

    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_ULTIMA_MODIFICACION", nullable = false, length = 0)
    public Date getFechaUltimaModificacion() {
        return this.fechaUltimaModificacion;
    }

    public void setFechaUltimaModificacion(Date fechaUltimaModificacion) {
        this.fechaUltimaModificacion = fechaUltimaModificacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_BAJA", length = 0)
    public Date getFechaBaja() {
        return this.fechaBaja;
    }

    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }


    @Column(name = "ESTADO", nullable = false, length = 1)
    public char getEstado() {
        return this.estado;
    }

    public void setEstado(char estado) {
        this.estado = estado;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "caracteristica")
    public List<CaracteristicaValor> getCaracteristicaValors() {
        return this.caracteristicaValors;
    }

    public void setCaracteristicaValors(List<CaracteristicaValor> caracteristicaValors) {
        this.caracteristicaValors = caracteristicaValors;
    }


}


