package com.disenio.entities.caracteristicas;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CaracteristicaValor generated by hbm2java
 */
@Entity
@Table(name="caracteristica_valor"
    ,catalog="patitas"
)
public class CaracteristicaValor  implements java.io.Serializable {


     private Integer idCaracteristicaValor;
     private Caracteristica caracteristica;
     private Valor valor;

    public CaracteristicaValor() {
    }

    public CaracteristicaValor(Caracteristica caracteristica, Valor valor) {
       this.caracteristica = caracteristica;
       this.valor = valor;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_CARACTERISTICA_VALOR", unique=true, nullable=false)
    public Integer getIdCaracteristicaValor() {
        return this.idCaracteristicaValor;
    }
    
    public void setIdCaracteristicaValor(Integer idCaracteristicaValor) {
        this.idCaracteristicaValor = idCaracteristicaValor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CARACTERISTICA", nullable=false)
    public Caracteristica getCaracteristica() {
        return this.caracteristica;
    }
    
    public void setCaracteristica(Caracteristica caracteristica) {
        this.caracteristica = caracteristica;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_VALOR", nullable=false)
    public Valor getValor() {
        return this.valor;
    }
    
    public void setValor(Valor valor) {
        this.valor = valor;
    }




}


