package com.disenio.entities.caracteristicas;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import com.disenio.entities.Views;
import com.fasterxml.jackson.annotation.JsonView;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ComportamientoTipo generated by hbm2java
 */
@Entity
@Table(name="comportamiento_tipo"
    ,catalog="patitas"
)
public class ComportamientoTipo  implements java.io.Serializable {

    @JsonView(Views.External.class)
     private Integer idComportamientoTipo;
    @JsonView(Views.External.class)
     private String descripcion;
    @JsonView(Views.Internal.class)
     private Set caracteristicas = new HashSet(0);

    public ComportamientoTipo() {
    }

	
    public ComportamientoTipo(String descripcion) {
        this.descripcion = descripcion;
    }
    public ComportamientoTipo(String descripcion, Set caracteristicas) {
       this.descripcion = descripcion;
       this.caracteristicas = caracteristicas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_COMPORTAMIENTO_TIPO", unique=true, nullable=false)
    public Integer getIdComportamientoTipo() {
        return this.idComportamientoTipo;
    }
    
    public void setIdComportamientoTipo(Integer idComportamientoTipo) {
        this.idComportamientoTipo = idComportamientoTipo;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=20)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comportamientoTipo")
    public Set<Caracteristica> getCaracteristicas() {
        return this.caracteristicas;
    }
    
    public void setCaracteristicas(Set caracteristicas) {
        this.caracteristicas = caracteristicas;
    }




}


