package com.disenio.entities.caracteristicas;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Valor generated by hbm2java
 */
@Entity
@Table(name="valor"
    ,catalog="patitas"
)
public class Valor  implements java.io.Serializable {


     private Integer idValor;
     private String descripcion;
     private Set caracteristicaValors = new HashSet(0);
     private Set caracteristicaDetalleValors = new HashSet(0);

    public Valor() {
    }

	
    public Valor(String descripcion) {
        this.descripcion = descripcion;
    }
    public Valor(String descripcion, Set caracteristicaValors, Set caracteristicaDetalleValors) {
       this.descripcion = descripcion;
       this.caracteristicaValors = caracteristicaValors;
       this.caracteristicaDetalleValors = caracteristicaDetalleValors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_VALOR", unique=true, nullable=false)
    public Integer getIdValor() {
        return this.idValor;
    }
    
    public void setIdValor(Integer idValor) {
        this.idValor = idValor;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=20)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="valor")
    public Set<CaracteristicaValor> getCaracteristicaValors() {
        return this.caracteristicaValors;
    }
    
    public void setCaracteristicaValors(Set caracteristicaValors) {
        this.caracteristicaValors = caracteristicaValors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="valor")
    public Set<CaracteristicaDetalleValor> getCaracteristicaDetalleValors() {
        return this.caracteristicaDetalleValors;
    }
    
    public void setCaracteristicaDetalleValors(Set caracteristicaDetalleValors) {
        this.caracteristicaDetalleValors = caracteristicaDetalleValors;
    }




}


