package com.disenio.entities.caracteristicas;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import com.disenio.entities.Views;
import com.fasterxml.jackson.annotation.JsonView;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Valor generated by hbm2java
 */
@Entity
@Table(name = "valor"
        , catalog = "patitas"
)
public class Valor implements java.io.Serializable {
    @JsonView(Views.External.class)
    private Integer idValor;
    @JsonView(Views.External.class)
    private String descripcion;

    public Valor() {
    }


    public Valor(String descripcion) {
        this.descripcion = descripcion;
    }


    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "ID_VALOR", unique = true, nullable = false)
    public Integer getIdValor() {
        return this.idValor;
    }

    public void setIdValor(Integer idValor) {
        this.idValor = idValor;
    }


    @Column(name = "DESCRIPCION", nullable = false, length = 20)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }


}


