package com.disenio.model.aplicativos;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Aplicativo generated by hbm2java
 */
@Entity
@Table(name="aplicativo"
    ,catalog="patitas"
)
public class Aplicativo  implements java.io.Serializable {


     private Integer idAplicativo;
     private String descripcion;
     private String observacion;
     private char estado;
     private Set aplicativoRols = new HashSet(0);

    public Aplicativo() {
    }

	
    public Aplicativo(String descripcion, String observacion, char estado) {
        this.descripcion = descripcion;
        this.observacion = observacion;
        this.estado = estado;
    }
    public Aplicativo(String descripcion, String observacion, char estado, Set aplicativoRols) {
       this.descripcion = descripcion;
       this.observacion = observacion;
       this.estado = estado;
       this.aplicativoRols = aplicativoRols;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_APLICATIVO", unique=true, nullable=false)
    public Integer getIdAplicativo() {
        return this.idAplicativo;
    }
    
    public void setIdAplicativo(Integer idAplicativo) {
        this.idAplicativo = idAplicativo;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="OBSERVACION", nullable=false, length=200)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="ESTADO", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="aplicativo")
    public Set<AplicativoRol> getAplicativoRols() {
        return this.aplicativoRols;
    }
    
    public void setAplicativoRols(Set aplicativoRols) {
        this.aplicativoRols = aplicativoRols;
    }




}


