package com.disenio.entities.aplicativos;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import com.disenio.entities.usuarios.UsuarioRol;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AplicativoRol generated by hbm2java
 */
@Entity
@Table(name="aplicativo_rol"
    ,catalog="patitas"
)
public class AplicativoRol  implements java.io.Serializable {


     private Integer idAplicativoRol;
     private Aplicativo aplicativo;
     private String descripcion;
     private char estado;
     private Set usuarioRols = new HashSet(0);

    public AplicativoRol() {
    }

	
    public AplicativoRol(Aplicativo aplicativo, String descripcion, char estado) {
        this.aplicativo = aplicativo;
        this.descripcion = descripcion;
        this.estado = estado;
    }
    public AplicativoRol(Aplicativo aplicativo, String descripcion, char estado, Set usuarioRols) {
       this.aplicativo = aplicativo;
       this.descripcion = descripcion;
       this.estado = estado;
       this.usuarioRols = usuarioRols;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_APLICATIVO_ROL", unique=true, nullable=false)
    public Integer getIdAplicativoRol() {
        return this.idAplicativoRol;
    }
    
    public void setIdAplicativoRol(Integer idAplicativoRol) {
        this.idAplicativoRol = idAplicativoRol;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_APLICATIVO", nullable=false)
    public Aplicativo getAplicativo() {
        return this.aplicativo;
    }
    
    public void setAplicativo(Aplicativo aplicativo) {
        this.aplicativo = aplicativo;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=20)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="ESTADO", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="aplicativoRol")
    public Set<UsuarioRol> getUsuarioRols() {
        return this.usuarioRols;
    }
    
    public void setUsuarioRols(Set usuarioRols) {
        this.usuarioRols = usuarioRols;
    }




}


