package com.disenio.models.personas;
// Generated 29/08/2021 23:04:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MedioNotificacion generated by hbm2java
 */
@Entity
@Table(name="medio_notificacion"
    ,catalog="patitas"
)
public class MedioNotificacion  implements java.io.Serializable {


     private Long idMedioNotificacion;
     private String descripcion;

    public MedioNotificacion() {
    }

	
    public MedioNotificacion(String descripcion) {
        this.descripcion = descripcion;
    }

     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_MEDIO_NOTIFICACION", unique=true, nullable=false)
    public Long getIdMedioNotificacion() {
        return this.idMedioNotificacion;
    }
    
    public void setIdMedioNotificacion(Long idMedioNotificacion) {
        this.idMedioNotificacion = idMedioNotificacion;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }



}


