package com.disenio.models.personas;
// Generated 29/08/2021 23:04:39 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PersonaContacto generated by hbm2java
 */
@Entity
@Table(name="persona_contacto"
    ,catalog="patitas"
)
public class PersonaContacto  implements java.io.Serializable {


     private Long idPersonaContacto;
     private Persona persona;
     private String nombre;
     private String apellido;
     private String email;
     private int telefono;
     private Date fechaAlta;
     private Date fechaUltimaModificion;
     private Date fechaBaja;
     private char estado;

    public PersonaContacto() {
    }

	
    public PersonaContacto(Persona persona, String nombre, String apellido, String email, int telefono, Date fechaAlta, Date fechaUltimaModificion, char estado) {
        this.persona = persona;
        this.nombre = nombre;
        this.apellido = apellido;
        this.email = email;
        this.telefono = telefono;
        this.fechaAlta = fechaAlta;
        this.fechaUltimaModificion = fechaUltimaModificion;
        this.estado = estado;
    }
    public PersonaContacto(Persona persona, String nombre, String apellido, String email, int telefono, Date fechaAlta, Date fechaUltimaModificion, Date fechaBaja, char estado) {
       this.persona = persona;
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.telefono = telefono;
       this.fechaAlta = fechaAlta;
       this.fechaUltimaModificion = fechaUltimaModificion;
       this.fechaBaja = fechaBaja;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_PERSONA_CONTACTO", unique=true, nullable=false)
    public Long getIdPersonaContacto() {
        return this.idPersonaContacto;
    }
    
    public void setIdPersonaContacto(Long idPersonaContacto) {
        this.idPersonaContacto = idPersonaContacto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PERSONA", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="APELLIDO", nullable=false, length=50)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="EMAIL", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="TELEFONO", nullable=false)
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ALTA", nullable=false, length=0)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ULTIMA_MODIFICION", nullable=false, length=0)
    public Date getFechaUltimaModificion() {
        return this.fechaUltimaModificion;
    }
    
    public void setFechaUltimaModificion(Date fechaUltimaModificion) {
        this.fechaUltimaModificion = fechaUltimaModificion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_BAJA", length=0)
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }

    
    @Column(name="ESTADO", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }




}


