package com.disenio.model.caracteristicas;
import com.disenio.model.mascotas.Mascota;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * CaracteristicaDetalle generated by hbm2java
 */
@Entity
@Data
@Table(name="caracteristica_detalle" ,catalog="patitas")
public class CaracteristicaDetalle  implements java.io.Serializable {

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="ID_DETALLE", unique=true, nullable=false)
    private Integer idDetalle;

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CARACTERISTICA", nullable=false)
    private Caracteristica caracteristica;

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_MASCOTA", nullable=false)
    private Mascota mascota;

    @Column(name="FECHA_ALTA", nullable=false, length=10)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy HH:mm", timezone = "GMT+8")
    private Calendar fechaAlta;

    @Column(name="FECHA_ULTIMA_MODIFICACION", nullable=false, length=10)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy HH:mm", timezone = "GMT+8")
    private Calendar fechaUltimaModificacion;

    @Column(name="FECHA_BAJA", length=10)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy HH:mm", timezone = "GMT+8")
    private Calendar fechaBaja;

    @Column(name="ESTADO", nullable=false, length=1)
    private char estado;

    @OneToMany(fetch=FetchType.LAZY, mappedBy="caracteristicaDetalle")
    private List<CaracteristicaDetalleValor> caracteristicaDetalleValors;


}


