package com.disenio.models.organizacion;
// Generated 29/08/2021 23:04:39 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NormalizaImg generated by hbm2java
 */
@Entity
@Table(name="normaliza_img"
    ,catalog="patitas"
)
public class NormalizaImg  implements java.io.Serializable {


     private Long idNormalizaImg;
     private Organizacion organizacion;
     private int ancho;
     private int largo;
     private int calidad;

    public NormalizaImg() {
    }

    public NormalizaImg(Organizacion organizacion, int ancho, int largo, int calidad) {
       this.organizacion = organizacion;
       this.ancho = ancho;
       this.largo = largo;
       this.calidad = calidad;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_NORMALIZA_IMG", unique=true, nullable=false)
    public Long getIdNormalizaImg() {
        return this.idNormalizaImg;
    }
    
    public void setIdNormalizaImg(Long idNormalizaImg) {
        this.idNormalizaImg = idNormalizaImg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ORGANIZACION", nullable=false)
    public Organizacion getOrganizacion() {
        return this.organizacion;
    }
    
    public void setOrganizacion(Organizacion organizacion) {
        this.organizacion = organizacion;
    }

    
    @Column(name="ANCHO", nullable=false)
    public int getAncho() {
        return this.ancho;
    }
    
    public void setAncho(int ancho) {
        this.ancho = ancho;
    }

    
    @Column(name="LARGO", nullable=false)
    public int getLargo() {
        return this.largo;
    }
    
    public void setLargo(int largo) {
        this.largo = largo;
    }

    
    @Column(name="CALIDAD", nullable=false)
    public int getCalidad() {
        return this.calidad;
    }
    
    public void setCalidad(int calidad) {
        this.calidad = calidad;
    }




}


