package com.disenio.models.organizacion;
// Generated 29/08/2021 23:04:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Organizacion generated by hbm2java
 */
@Entity
@Table(name="organizacion"
    ,catalog="patitas"
)
public class Organizacion  implements java.io.Serializable {


     private Long idOrganizacion;
     private String nombre;
     private String urlNomalizador;
     private char estado;

    public Organizacion() {
    }

	
    public Organizacion(String nombre, String urlNomalizador, char estado) {
        this.nombre = nombre;
        this.urlNomalizador = urlNomalizador;
        this.estado = estado;
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_ORGANIZACION", unique=true, nullable=false)
    public Long getIdOrganizacion() {
        return this.idOrganizacion;
    }
    
    public void setIdOrganizacion(Long idOrganizacion) {
        this.idOrganizacion = idOrganizacion;
    }

    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="URL_NOMALIZADOR", nullable=false, length=200)
    public String getUrlNomalizador() {
        return this.urlNomalizador;
    }
    
    public void setUrlNomalizador(String urlNomalizador) {
        this.urlNomalizador = urlNomalizador;
    }

    
    @Column(name="ESTADO", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }



}


