package com.disenio.models.usuarios;
// Generated 29/08/2021 23:04:39 by Hibernate Tools 4.3.1


import com.disenio.models.organizacion.Organizacion;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UsuarioOrganizacion generated by hbm2java
 */
@Entity
@Table(name="usuario_organizacion"
    ,catalog="patitas"
)
public class UsuarioOrganizacion  implements java.io.Serializable {


     private Long idUsuarioOrg;
     private Organizacion organizacion;
     private Usuario usuario;
     private char estado;

    public UsuarioOrganizacion() {
    }

	
    public UsuarioOrganizacion(Organizacion organizacion, Usuario usuario, char estado) {
        this.organizacion = organizacion;
        this.usuario = usuario;
        this.estado = estado;
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_USUARIO_ORG", unique=true, nullable=false)
    public Long getIdUsuarioOrg() {
        return this.idUsuarioOrg;
    }
    
    public void setIdUsuarioOrg(Long idUsuarioOrg) {
        this.idUsuarioOrg = idUsuarioOrg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ORGANIZACION", nullable=false)
    public Organizacion getOrganizacion() {
        return this.organizacion;
    }
    
    public void setOrganizacion(Organizacion organizacion) {
        this.organizacion = organizacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USUARIO", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="ESTADO", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }



}


