package com.disenio.entities.organizacion;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import com.disenio.entities.Views;
import com.disenio.entities.caracteristicas.Caracteristica;
import com.disenio.entities.usuarios.UsuarioOrganizacion;
import com.fasterxml.jackson.annotation.JsonView;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Organizacion generated by hbm2java
 */
@Entity
@Table(name = "organizacion"
        , catalog = "patitas"
)
public class Organizacion implements java.io.Serializable {

    @JsonView(Views.External.class)
    private Integer idOrganizacion;
    @JsonView(Views.External.class)
    private String nombre;
    @JsonView(Views.External.class)
    private String urlNomalizador;
    @JsonView(Views.External.class)
    private char estado;
    @JsonView(Views.Internal.class)
    private Set usuarioOrganizacions = new HashSet(0);
    @JsonView(Views.Internal.class)
    private Set caracteristicas = new HashSet(0);
    @JsonView(Views.Internal.class)
    private Set normalizaImgs = new HashSet(0);

    public Organizacion() {
    }


    public Organizacion(String nombre, String urlNomalizador, char estado) {
        this.nombre = nombre;
        this.urlNomalizador = urlNomalizador;
        this.estado = estado;
    }

    public Organizacion(String nombre, String urlNomalizador, char estado, Set usuarioOrganizacions, Set caracteristicas, Set normalizaImgs) {
        this.nombre = nombre;
        this.urlNomalizador = urlNomalizador;
        this.estado = estado;
        this.usuarioOrganizacions = usuarioOrganizacions;
        this.caracteristicas = caracteristicas;
        this.normalizaImgs = normalizaImgs;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "ID_ORGANIZACION", unique = true, nullable = false)
    public Integer getIdOrganizacion() {
        return this.idOrganizacion;
    }

    public void setIdOrganizacion(Integer idOrganizacion) {
        this.idOrganizacion = idOrganizacion;
    }


    @Column(name = "NOMBRE", nullable = false, length = 50)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


    @Column(name = "URL_NOMALIZADOR", nullable = false, length = 200)
    public String getUrlNomalizador() {
        return this.urlNomalizador;
    }

    public void setUrlNomalizador(String urlNomalizador) {
        this.urlNomalizador = urlNomalizador;
    }


    @Column(name = "ESTADO", nullable = false, length = 1)
    public char getEstado() {
        return this.estado;
    }

    public void setEstado(char estado) {
        this.estado = estado;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "organizacion")
    public Set<UsuarioOrganizacion> getUsuarioOrganizacions() {
        return this.usuarioOrganizacions;
    }

    public void setUsuarioOrganizacions(Set usuarioOrganizacions) {
        this.usuarioOrganizacions = usuarioOrganizacions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "organizacion")
    public Set<Caracteristica> getCaracteristicas() {
        return this.caracteristicas;
    }

    public void setCaracteristicas(Set caracteristicas) {
        this.caracteristicas = caracteristicas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "organizacion")
    public Set<NormalizaImg> getNormalizaImgs() {
        return this.normalizaImgs;
    }

    public void setNormalizaImgs(Set normalizaImgs) {
        this.normalizaImgs = normalizaImgs;
    }


}


