package com.disenio.entities.usuarios;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import com.disenio.entities.personas.Persona;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="patitas"
)
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Persona persona;
     private String nombre;
     private String clave;
     private Date fechaAlta;
     private Date fechaUltimaModificacion;
     private Integer fechaBaja;
     private int cantidadLogin;
     private char estado;
     private Set usuarioOrganizacions = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(Persona persona, String nombre, String clave, Date fechaAlta, Date fechaUltimaModificacion, int cantidadLogin, char estado) {
        this.persona = persona;
        this.nombre = nombre;
        this.clave = clave;
        this.fechaAlta = fechaAlta;
        this.fechaUltimaModificacion = fechaUltimaModificacion;
        this.cantidadLogin = cantidadLogin;
        this.estado = estado;
    }
    public Usuario(Persona persona, String nombre, String clave, Date fechaAlta, Date fechaUltimaModificacion, Integer fechaBaja, int cantidadLogin, char estado, Set usuarioOrganizacions) {
       this.persona = persona;
       this.nombre = nombre;
       this.clave = clave;
       this.fechaAlta = fechaAlta;
       this.fechaUltimaModificacion = fechaUltimaModificacion;
       this.fechaBaja = fechaBaja;
       this.cantidadLogin = cantidadLogin;
       this.estado = estado;
       this.usuarioOrganizacions = usuarioOrganizacions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_USUARIO", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PERSONA", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="CLAVE", nullable=false, length=80)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ALTA", nullable=false, length=0)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ULTIMA_MODIFICACION", nullable=false, length=0)
    public Date getFechaUltimaModificacion() {
        return this.fechaUltimaModificacion;
    }
    
    public void setFechaUltimaModificacion(Date fechaUltimaModificacion) {
        this.fechaUltimaModificacion = fechaUltimaModificacion;
    }

    
    @Column(name="FECHA_BAJA")
    public Integer getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Integer fechaBaja) {
        this.fechaBaja = fechaBaja;
    }

    
    @Column(name="CANTIDAD_LOGIN", nullable=false)
    public int getCantidadLogin() {
        return this.cantidadLogin;
    }
    
    public void setCantidadLogin(int cantidadLogin) {
        this.cantidadLogin = cantidadLogin;
    }

    
    @Column(name="ESTADO", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<UsuarioOrganizacion> getUsuarioOrganizacions() {
        return this.usuarioOrganizacions;
    }
    
    public void setUsuarioOrganizacions(Set usuarioOrganizacions) {
        this.usuarioOrganizacions = usuarioOrganizacions;
    }




}


