package com.disenio.model.mascotas;

import com.disenio.model.faq.FaqRespuestaValor;
import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CaracteristicaDetalleValor generated by grupo 10
 */
/*
@Entity
@Data
@Table(name="caracteristica_detalle_valor",catalog="patitas"
)
public class CaracteristicaDetalleValor  implements java.io.Serializable {

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="ID_DETALLE_VALOR", unique=true, nullable=false)
     private Integer idDetalleValor;

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_DETALLE", nullable=false)
     private CaracteristicaDetalle caracteristicaDetalle;
///Caracteristica detalle -< CaracteristicaDetalleValor >- FaqRespuestaValor
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_RESPUESTAS_VALOR", nullable=false)
     private FaqRespuestaValor faqRespuestaValor;

    @Column(name="ESTADO", nullable=false, length=1)
     private char estado;




}
*/

