package com.disenio.model.mascotas;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import com.disenio.model.caracteristicas.CaracteristicaDetalle;
import com.disenio.model.personas.Persona;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mascota generated by hbm2java
 */
@Entity
@Table(name="mascota"
    ,catalog="patitas"
)
public class Mascota  implements java.io.Serializable {


     private Integer idMascota;
     private Persona persona;
     private SexoMascota sexoMascota;
     private TipoMascota tipoMascota;
     private String nombre;
     private String apodo;
     private Date fechaNacimiento;
     private String descripcionFisica;
     private Date fechaAlta;
     private Date fechaUltimaModificacion;
     private Date fechaBaja;
     private char estado;
     private Set caracteristicaDetalles = new HashSet(0);
     private Set mascotaFotos = new HashSet(0);

    public Mascota() {
    }

	
    public Mascota(Persona persona, SexoMascota sexoMascota, TipoMascota tipoMascota, String nombre, String apodo, Date fechaNacimiento, String descripcionFisica, Date fechaAlta, Date fechaUltimaModificacion, char estado) {
        this.persona = persona;
        this.sexoMascota = sexoMascota;
        this.tipoMascota = tipoMascota;
        this.nombre = nombre;
        this.apodo = apodo;
        this.fechaNacimiento = fechaNacimiento;
        this.descripcionFisica = descripcionFisica;
        this.fechaAlta = fechaAlta;
        this.fechaUltimaModificacion = fechaUltimaModificacion;
        this.estado = estado;
    }
    public Mascota(Persona persona, SexoMascota sexoMascota, TipoMascota tipoMascota, String nombre, String apodo, Date fechaNacimiento, String descripcionFisica, Date fechaAlta, Date fechaUltimaModificacion, Date fechaBaja, char estado, Set caracteristicaDetalles, Set mascotaFotos) {
       this.persona = persona;
       this.sexoMascota = sexoMascota;
       this.tipoMascota = tipoMascota;
       this.nombre = nombre;
       this.apodo = apodo;
       this.fechaNacimiento = fechaNacimiento;
       this.descripcionFisica = descripcionFisica;
       this.fechaAlta = fechaAlta;
       this.fechaUltimaModificacion = fechaUltimaModificacion;
       this.fechaBaja = fechaBaja;
       this.estado = estado;
       this.caracteristicaDetalles = caracteristicaDetalles;
       this.mascotaFotos = mascotaFotos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_MASCOTA", unique=true, nullable=false)
    public Integer getIdMascota() {
        return this.idMascota;
    }
    
    public void setIdMascota(Integer idMascota) {
        this.idMascota = idMascota;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_PERSONA", nullable=false)
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_SEXO", nullable=false)
    public SexoMascota getSexoMascota() {
        return this.sexoMascota;
    }
    
    public void setSexoMascota(SexoMascota sexoMascota) {
        this.sexoMascota = sexoMascota;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_TIPO_MASCOTA", nullable=false)
    public TipoMascota getTipoMascota() {
        return this.tipoMascota;
    }
    
    public void setTipoMascota(TipoMascota tipoMascota) {
        this.tipoMascota = tipoMascota;
    }

    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="APODO", nullable=false, length=50)
    public String getApodo() {
        return this.apodo;
    }
    
    public void setApodo(String apodo) {
        this.apodo = apodo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_NACIMIENTO", nullable=false, length=0)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    
    @Column(name="DESCRIPCION_FISICA", nullable=false, length=2000)
    public String getDescripcionFisica() {
        return this.descripcionFisica;
    }
    
    public void setDescripcionFisica(String descripcionFisica) {
        this.descripcionFisica = descripcionFisica;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ALTA", nullable=false, length=0)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ULTIMA_MODIFICACION", nullable=false, length=0)
    public Date getFechaUltimaModificacion() {
        return this.fechaUltimaModificacion;
    }
    
    public void setFechaUltimaModificacion(Date fechaUltimaModificacion) {
        this.fechaUltimaModificacion = fechaUltimaModificacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_BAJA", length=0)
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }

    
    @Column(name="ESTADO", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mascota")
    public Set<CaracteristicaDetalle> getCaracteristicaDetalles() {
        return this.caracteristicaDetalles;
    }
    
    public void setCaracteristicaDetalles(Set caracteristicaDetalles) {
        this.caracteristicaDetalles = caracteristicaDetalles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mascota")
    public Set<MascotaFoto> getMascotaFotos() {
        return this.mascotaFotos;
    }
    
    public void setMascotaFotos(Set mascotaFotos) {
        this.mascotaFotos = mascotaFotos;
    }




}


