package com.disenio.model.mascotas;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.time.LocalDate;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * MascotaHogarTransito generated by hbm2java
 */
@Entity
@Table(name = "mascota_hogar_transito"
        , catalog = "patitas"
)
public class MascotaHogarTransito implements java.io.Serializable {


    private Integer idMascotaHogar;
    // private MascotaRescatada mascotaRescatada;
    private int idHogar;
    private Date fechaAlta;
    private Date fechaUltimaModificacion;
    private Date fechaBaja;
    private char estado;

    public MascotaHogarTransito() {
    }

    public MascotaHogarTransito(int id) {
        this.idHogar = id;
        this.fechaAlta = java.sql.Date.valueOf(LocalDate.now());
        this.fechaUltimaModificacion = java.sql.Date.valueOf(LocalDate.now());
        this.fechaBaja = java.sql.Date.valueOf(LocalDate.now());
        this.estado = 'A';
    }


    public MascotaHogarTransito(MascotaRescatada mascotaRescatada, int idHogar, Date fechaAlta, Date fechaUltimaModificacion, char estado) {
        //this.mascotaRescatada = mascotaRescatada;
        this.idHogar = idHogar;
        this.fechaAlta = fechaAlta;
        this.fechaUltimaModificacion = fechaUltimaModificacion;
        this.estado = estado;
    }

    public MascotaHogarTransito(MascotaRescatada mascotaRescatada, int idHogar, Date fechaAlta, Date fechaUltimaModificacion, Date fechaBaja, char estado) {
        // this.mascotaRescatada = mascotaRescatada;
        this.idHogar = idHogar;
        this.fechaAlta = fechaAlta;
        this.fechaUltimaModificacion = fechaUltimaModificacion;
        this.fechaBaja = fechaBaja;
        this.estado = estado;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID_MASCOTA_HOGAR", unique = true, nullable = false)
    public Integer getIdMascotaHogar() {
        return this.idMascotaHogar;
    }

    public void setIdMascotaHogar(Integer idMascotaHogar) {
        this.idMascotaHogar = idMascotaHogar;
    }
/*
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_MASCOTA_RESCATADA", nullable=false)
    public MascotaRescatada getMascotaRescatada() {
        return this.mascotaRescatada;
    }
    
    public void setMascotaRescatada(MascotaRescatada mascotaRescatada) {
        this.mascotaRescatada = mascotaRescatada;
    }
*/

    @Column(name = "ID_HOGAR", nullable = false)
    public int getIdHogar() {
        return this.idHogar;
    }

    public void setIdHogar(int idHogar) {
        this.idHogar = idHogar;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_ALTA", nullable = false, length = 0)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }

    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_ULTIMA_MODIFICACION", nullable = false, length = 0)
    public Date getFechaUltimaModificacion() {
        return this.fechaUltimaModificacion;
    }

    public void setFechaUltimaModificacion(Date fechaUltimaModificacion) {
        this.fechaUltimaModificacion = fechaUltimaModificacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_BAJA", length = 0)
    public Date getFechaBaja() {
        return this.fechaBaja;
    }

    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }


    @Column(name = "ESTADO", nullable = false, length = 1)
    public char getEstado() {
        return this.estado;
    }

    public void setEstado(char estado) {
        this.estado = estado;
    }


}


