package com.disenio.model.mascotas;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SexoMascota generated by hbm2java
 */
@Entity
@Table(name="sexo_mascota"
    ,catalog="patitas"
)
public class SexoMascota  implements java.io.Serializable {


     private Integer idSexo;
     private String descripcion;
     private Set mascotas = new HashSet(0);

    public SexoMascota() {
    }

	
    public SexoMascota(String descripcion) {
        this.descripcion = descripcion;
    }
    public SexoMascota(String descripcion, Set mascotas) {
       this.descripcion = descripcion;
       this.mascotas = mascotas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_SEXO", unique=true, nullable=false)
    public Integer getIdSexo() {
        return this.idSexo;
    }
    
    public void setIdSexo(Integer idSexo) {
        this.idSexo = idSexo;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=10)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sexoMascota")
    public Set<Mascota> getMascotas() {
        return this.mascotas;
    }
    
    public void setMascotas(Set mascotas) {
        this.mascotas = mascotas;
    }




}


