package com.disenio.model.mascotas;


import lombok.Data;

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SexoMascota generated by Grupo 10
 */
@Entity
@Data
@Table(name = "sexo_mascota", catalog = "patitas")
public class SexoMascota implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID_SEXO", unique = true, nullable = false)
    private Integer idSexo;

    @Column(name = "DESCRIPCION", nullable = false, length = 10)
    private String descripcion;

   /* @OneToMany(fetch = FetchType.LAZY, mappedBy = "sexoMascota")
    private List<Mascota> mascotas;*/

}


