package com.disenio.model.mascotas;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TamanioMascota generated by hbm2java
 */
@Entity
@Table(name = "tamanio_mascota"
        , catalog = "patitas"
)
public class TamanioMascota implements java.io.Serializable {

    private Integer idTamanio;
    private String descripcion;
    private char estado;
    //private Set mascotaRescatadas = new HashSet(0);

    public TamanioMascota() {
    }

    public TamanioMascota(String descripcion) {
        this.descripcion = descripcion;
        this.estado = 'A';
    }


    public TamanioMascota(String descripcion, char estado) {
        this.descripcion = descripcion;
        this.estado = estado;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)


    @Column(name = "ID_TAMANIO", unique = true, nullable = false)
    public Integer getIdTamanio() {
        return this.idTamanio;
    }

    public void setIdTamanio(Integer idTamanio) {
        this.idTamanio = idTamanio;
    }


    @Column(name = "DESCRIPCION", nullable = false, length = 50)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }


    @Column(name = "ESTADO", nullable = false, length = 1)
    public char getEstado() {
        return this.estado;
    }

    public void setEstado(char estado) {
        this.estado = estado;
    }

}


