package com.disenio.model.mascotas;


import com.disenio.model.Views;
import com.fasterxml.jackson.annotation.JsonView;
import lombok.Data;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TipoMascota generated by Grupo 10
 */
@Entity
@Data
@Table(name = "tipo_mascota", catalog = "patitas")
public class TipoMascota implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID_TIPO_MASCOTA", unique = true, nullable = false)
    @JsonView(Views.External.class)
    private Integer idTipoMascota;

    @Column(name = "NOMBRE", nullable = false, length = 50)
    @JsonView(Views.External.class)
    private String nombre;
/*
    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoMascota")
    private Set<MascotaRescatada> mascotaRescatadas = new HashSet(0);

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoMascota")
    private Set<Mascota> mascotas = new HashSet(0);
*/

}


