package com.disenio.model.mascotas;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoMascota generated by hbm2java
 */
@Entity
@Data
@Table(name = "tipo_mascota" , catalog = "patitas")
public class TipoMascota implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID_TIPO_MASCOTA", unique = true, nullable = false)
    private Integer idTipoMascota;

    @Column(name = "NOMBRE", nullable = false, length = 50)
    private String nombre;

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoMascota")
    private Set<MascotaRescatada> mascotaRescatadas = new HashSet(0);

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoMascota")
    private Set<Mascota> mascotas = new HashSet(0);


}


