package com.disenio.model.mascotas;


import lombok.Data;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TipoMascota generated by Grupo 10
 */
@Entity
@Data
@Table(name = "tipo_mascota", catalog = "patitas")
public class TipoMascota implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID_TIPO_MASCOTA", unique = true, nullable = false)
    private Integer idTipoMascota;

    @Column(name = "NOMBRE", nullable = false, length = 50)
    private String nombre;

}


