package com.disenio.model.mascotas;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.time.LocalDate;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * UbicacionMascotaRescatada generated by hbm2java
 */
@Entity
@Table(name = "ubicacion_mascota_rescatada"
        , catalog = "patitas"
)
public class UbicacionMascotaRescatada implements java.io.Serializable {


    private Integer idUbicacion;
    // private MascotaRescatada mascotaRescatada;
    private String direccion;
    private Integer latitud;
    private Integer longitud;
    private Date fechaAlta;
    private Date fechaUltimaModificacion;
    private Date fechaBaja;
    private char estado;

    public UbicacionMascotaRescatada() {
    }

    public UbicacionMascotaRescatada(String direccion, Integer latitud, Integer longitud) {
        this.direccion = direccion;
        this.latitud = latitud;
        this.longitud = longitud;
        this.fechaAlta = java.sql.Date.valueOf(LocalDate.now());
        this.fechaUltimaModificacion = java.sql.Date.valueOf(LocalDate.now());
        //this.fechaBaja = fechaBaja;
        this.estado = 'A';
    }

    public UbicacionMascotaRescatada(String direccion, Date fechaAlta, Date fechaUltimaModificacion, char estado) {
        this.direccion = direccion;
        this.fechaAlta = fechaAlta;
        this.fechaUltimaModificacion = fechaUltimaModificacion;
        this.estado = estado;
    }

    public UbicacionMascotaRescatada(MascotaRescatada mascotaRescatada, String direccion, Integer latitud, Integer longitud, Date fechaAlta, Date fechaUltimaModificacion, Date fechaBaja, char estado) {
        this.direccion = direccion;
        this.latitud = latitud;
        this.longitud = longitud;
        this.fechaAlta = fechaAlta;
        this.fechaUltimaModificacion = fechaUltimaModificacion;
        this.fechaBaja = fechaBaja;
        this.estado = estado;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID_UBICACION", unique = true, nullable = false)
    public Integer getIdUbicacion() {
        return this.idUbicacion;
    }

    public void setIdUbicacion(Integer idUbicacion) {
        this.idUbicacion = idUbicacion;
    }


    @Column(name = "DIRECCION", nullable = false, length = 200)
    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }


    @Column(name = "LATITUD")
    public Integer getLatitud() {
        return this.latitud;
    }

    public void setLatitud(Integer latitud) {
        this.latitud = latitud;
    }


    @Column(name = "LONGITUD")
    public Integer getLongitud() {
        return this.longitud;
    }

    public void setLongitud(Integer longitud) {
        this.longitud = longitud;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_ALTA", nullable = false, length = 0)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }

    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_ULTIMA_MODIFICACION", nullable = false, length = 0)
    public Date getFechaUltimaModificacion() {
        return this.fechaUltimaModificacion;
    }

    public void setFechaUltimaModificacion(Date fechaUltimaModificacion) {
        this.fechaUltimaModificacion = fechaUltimaModificacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA_BAJA", length = 0)
    public Date getFechaBaja() {
        return this.fechaBaja;
    }

    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }


    @Column(name = "ESTADO", nullable = false, length = 1)
    public char getEstado() {
        return this.estado;
    }

    public void setEstado(char estado) {
        this.estado = estado;
    }


}


