package com.disenio.model.notificacion;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import com.disenio.model.personas.PersonaContacto;
import lombok.Data;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * MedioNotificacion generated by grupo 10
 */
@Entity
@Data
@Table(name = "medio_notificacion", catalog = "patitas")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "tipo_notificacion")
public abstract class MedioNotificacion {
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID_NOTIFICACION", unique = true, nullable = false)
    protected Integer idMedioNotificacion;

    @Column(name = "DESCRIPCION", nullable = false)
    protected String descripcion;

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public abstract void notificar(PersonaContacto personaContacto, String msg);

}


