package com.disenio.entities.personas;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MedioNotificacion generated by hbm2java
 */
@Entity
@Table(name="medio_notificacion"
    ,catalog="patitas"
)
public class MedioNotificacion  implements java.io.Serializable {


     private Integer idMedioNotificacion;
     private String descripcion;
     private Set contactoMedioNotificacions = new HashSet(0);

    public MedioNotificacion() {
    }

	
    public MedioNotificacion(String descripcion) {
        this.descripcion = descripcion;
    }
    public MedioNotificacion(String descripcion, Set contactoMedioNotificacions) {
       this.descripcion = descripcion;
       this.contactoMedioNotificacions = contactoMedioNotificacions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_MEDIO_NOTIFICACION", unique=true, nullable=false)
    public Integer getIdMedioNotificacion() {
        return this.idMedioNotificacion;
    }
    
    public void setIdMedioNotificacion(Integer idMedioNotificacion) {
        this.idMedioNotificacion = idMedioNotificacion;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medioNotificacion")
    public Set<ContactoMedioNotificacion> getContactoMedioNotificacions() {
        return this.contactoMedioNotificacions;
    }
    
    public void setContactoMedioNotificacions(Set contactoMedioNotificacions) {
        this.contactoMedioNotificacions = contactoMedioNotificacions;
    }




}


