package com.disenio.entities.personas;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import com.disenio.entities.mascotas.Mascota;
import com.disenio.entities.mascotas.MascotaRescatada;
import com.disenio.entities.usuarios.Usuario;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="persona"
    ,catalog="patitas"
)
public class Persona  implements java.io.Serializable {


     private Integer idPersona;
     private String nombre;
     private String apellido;
     private Date fechaNacimiento;
     private Date fechaAlta;
     private Date fechaUltimaModificacion;
     private Date fechaBaja;
     private char estado;
     private Set personaDocumentos = new HashSet(0);
     private Set personaContactos = new HashSet(0);
     private Set personaDireccions = new HashSet(0);
     private Set mascotas = new HashSet(0);
     private Set usuarios = new HashSet(0);
     private Set mascotaRescatadas = new HashSet(0);

    public Persona() {
    }

	
    public Persona(String nombre, String apellido, Date fechaNacimiento, Date fechaAlta, Date fechaUltimaModificacion, char estado) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.fechaNacimiento = fechaNacimiento;
        this.fechaAlta = fechaAlta;
        this.fechaUltimaModificacion = fechaUltimaModificacion;
        this.estado = estado;
    }
    public Persona(String nombre, String apellido, Date fechaNacimiento, Date fechaAlta, Date fechaUltimaModificacion, Date fechaBaja, char estado, Set personaDocumentos, Set personaContactos, Set personaDireccions, Set mascotas, Set usuarios, Set mascotaRescatadas) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechaNacimiento = fechaNacimiento;
       this.fechaAlta = fechaAlta;
       this.fechaUltimaModificacion = fechaUltimaModificacion;
       this.fechaBaja = fechaBaja;
       this.estado = estado;
       this.personaDocumentos = personaDocumentos;
       this.personaContactos = personaContactos;
       this.personaDireccions = personaDireccions;
       this.mascotas = mascotas;
       this.usuarios = usuarios;
       this.mascotaRescatadas = mascotaRescatadas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_PERSONA", unique=true, nullable=false)
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }

    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="APELLIDO", nullable=false, length=50)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_NACIMIENTO", nullable=false, length=0)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ALTA", nullable=false, length=0)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ULTIMA_MODIFICACION", nullable=false, length=0)
    public Date getFechaUltimaModificacion() {
        return this.fechaUltimaModificacion;
    }
    
    public void setFechaUltimaModificacion(Date fechaUltimaModificacion) {
        this.fechaUltimaModificacion = fechaUltimaModificacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_BAJA", length=0)
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }

    
    @Column(name="ESTADO", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set<PersonaDocumento> getPersonaDocumentos() {
        return this.personaDocumentos;
    }
    
    public void setPersonaDocumentos(Set personaDocumentos) {
        this.personaDocumentos = personaDocumentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set<PersonaContacto> getPersonaContactos() {
        return this.personaContactos;
    }
    
    public void setPersonaContactos(Set personaContactos) {
        this.personaContactos = personaContactos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set<PersonaDireccion> getPersonaDireccions() {
        return this.personaDireccions;
    }
    
    public void setPersonaDireccions(Set personaDireccions) {
        this.personaDireccions = personaDireccions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set<Mascota> getMascotas() {
        return this.mascotas;
    }
    
    public void setMascotas(Set mascotas) {
        this.mascotas = mascotas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set<MascotaRescatada> getMascotaRescatadas() {
        return this.mascotaRescatadas;
    }
    
    public void setMascotaRescatadas(Set mascotaRescatadas) {
        this.mascotaRescatadas = mascotaRescatadas;
    }




}


