package com.disenio.model.cuestionario;
/**
 * generated by grupo10
 */

import com.disenio.model.faq.Faq;
import com.disenio.model.faq.FaqRespuestaValor;

import javax.persistence.*;
import java.util.List;

import static javax.persistence.GenerationType.IDENTITY;

@Entity
@Table(name = "entrada_cuestionario", catalog = "patitas"
)
public class EntradaCuestionario implements Cloneable {
    private Integer idEntradaCuestionario;

    private Faq faq;
    private List<FaqRespuestaValor> respuesta;

    //Constructors


    public EntradaCuestionario(Integer idEntradaCuestionario, Faq faq, List<FaqRespuestaValor> respuesta) {
        this.idEntradaCuestionario = idEntradaCuestionario;
        this.faq = faq;
        this.respuesta = respuesta;
    }

    public EntradaCuestionario(Faq faq, List<FaqRespuestaValor> respuesta) {
        this.faq = faq;
        this.respuesta = respuesta;
    }

    public EntradaCuestionario() {

    }

    //Accessors

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID_ENTRADA_CUESTIONARIO", unique = true, nullable = false)
    public Integer getIdEntradaCuestionario() {
        return idEntradaCuestionario;
    }

    public void setIdEntradaCuestionario(Integer idEntradaCuestionario) {
        this.idEntradaCuestionario = idEntradaCuestionario;
    }


    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_FAQ", nullable = false)
    public Faq getFaq() {
        return faq;
    }

    public void setFaq(Faq faq) {
        this.faq = faq;
    }

    @OneToMany(fetch = FetchType.LAZY)
    @Column(name = "ID_RESPUESTA_VALOR")
    public List<FaqRespuestaValor> getRespuesta() {
        return respuesta;
    }

    public void setRespuesta(List<FaqRespuestaValor> respuesta) {
        this.respuesta = respuesta;
    }

    //Funcionalidada
    @Override
    public EntradaCuestionario clone() {
        return new EntradaCuestionario(faq, respuesta);
    }
}
