package com.disenio.model.cuestionario;
/**
 * generated by grupo10
 */
import com.disenio.model.faq.Faq;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

@Entity
@Table(name = "entrada_cuestionario", catalog = "patitas"
)
public class EntradaCuestionario implements Cloneable {
    private Integer idEntradaCuestionario;
    private Boolean esPreferencia;
    private Boolean esComodidad;
    private Faq faq;

    //Constructors
    public EntradaCuestionario(Boolean esPreferencia, Boolean esComodidad, Faq faq) {
        this.esPreferencia = esPreferencia;
        this.esComodidad = esComodidad;
        this.faq = faq;
    }

    public EntradaCuestionario() {

    }

    //Accessors

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID_ENTRADA_CUESTIONARIO", unique = true, nullable = false)
    public Integer getIdEntradaCuestionario() {
        return idEntradaCuestionario;
    }

    public void setIdEntradaCuestionario(Integer idEntradaCuestionario) {
        this.idEntradaCuestionario = idEntradaCuestionario;
    }

    @Column(name = "ES_PREFERENCIA", nullable = false)
    public Boolean getEsPreferencia() {
        return esPreferencia;
    }

    public void setEsPreferencia(Boolean esPreferencia) {
        this.esPreferencia = esPreferencia;
    }

    @Column(name = "ES_COMODIDAD", nullable = false)
    public Boolean getEsComodidad() {
        return esComodidad;
    }

    public void setEsComodidad(Boolean esComodidad) {
        this.esComodidad = esComodidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_FAQ", nullable = false)
    public Faq getFaq() {
        return faq;
    }

    public void setFaq(Faq faq) {
        this.faq = faq;
    }

    //Funcionalidada
    @Override
    public EntradaCuestionario clone() {
        return new EntradaCuestionario(esPreferencia, esComodidad, faq);
    }
}
