package com.disenio.models.mascotas;
// Generated 29/08/2021 23:04:39 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MascotaFoto generated by hbm2java
 */
@Entity
@Table(name="mascota_foto"
    ,catalog="patitas"
)
public class MascotaFoto  implements java.io.Serializable {


     private Long idMascotaFoto;
     private Mascota mascota;
     private MascotaRescatada mascotaRescatada;
     private byte[] valorFoto;
     private Date fechaAlta;
     private Date fechaUltimaModificacion;
     private Date fechaBaja;
     private char estado;

    public MascotaFoto() {
    }

	
    public MascotaFoto(byte[] valorFoto, Date fechaAlta, Date fechaUltimaModificacion, char estado) {
        this.valorFoto = valorFoto;
        this.fechaAlta = fechaAlta;
        this.fechaUltimaModificacion = fechaUltimaModificacion;
        this.estado = estado;
    }
    public MascotaFoto(Mascota mascota, MascotaRescatada mascotaRescatada, byte[] valorFoto, Date fechaAlta, Date fechaUltimaModificacion, Date fechaBaja, char estado) {
       this.mascota = mascota;
       this.mascotaRescatada = mascotaRescatada;
       this.valorFoto = valorFoto;
       this.fechaAlta = fechaAlta;
       this.fechaUltimaModificacion = fechaUltimaModificacion;
       this.fechaBaja = fechaBaja;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_MASCOTA_FOTO", unique=true, nullable=false)
    public Long getIdMascotaFoto() {
        return this.idMascotaFoto;
    }
    
    public void setIdMascotaFoto(Long idMascotaFoto) {
        this.idMascotaFoto = idMascotaFoto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_MASCOTA")
    public Mascota getMascota() {
        return this.mascota;
    }
    
    public void setMascota(Mascota mascota) {
        this.mascota = mascota;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_MASCOTA_RESCATADA")
    public MascotaRescatada getMascotaRescatada() {
        return this.mascotaRescatada;
    }
    
    public void setMascotaRescatada(MascotaRescatada mascotaRescatada) {
        this.mascotaRescatada = mascotaRescatada;
    }

    
    @Column(name="VALOR_FOTO", nullable=false)
    public byte[] getValorFoto() {
        return this.valorFoto;
    }
    
    public void setValorFoto(byte[] valorFoto) {
        this.valorFoto = valorFoto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ALTA", nullable=false, length=0)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ULTIMA_MODIFICACION", nullable=false, length=0)
    public Date getFechaUltimaModificacion() {
        return this.fechaUltimaModificacion;
    }
    
    public void setFechaUltimaModificacion(Date fechaUltimaModificacion) {
        this.fechaUltimaModificacion = fechaUltimaModificacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_BAJA", length=0)
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }

    
    @Column(name="ESTADO", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }




}


