package com.disenio.models.mascotas;
// Generated 29/08/2021 23:04:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SexoMascota generated by hbm2java
 */
@Entity
@Table(name="sexo_mascota"
    ,catalog="patitas"
)
public class SexoMascota  implements java.io.Serializable {


     private Long idSexo;
     private String descripcion;

    public SexoMascota() {
    }

	
    public SexoMascota(String descripcion) {
        this.descripcion = descripcion;
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_SEXO", unique=true, nullable=false)
    public Long getIdSexo() {
        return this.idSexo;
    }
    
    public void setIdSexo(Long idSexo) {
        this.idSexo = idSexo;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=10)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


