package com.disenio.models.mascotas;
// Generated 29/08/2021 23:04:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TamanioMascota generated by hbm2java
 */
@Entity
@Table(name="tamanio_mascota"
    ,catalog="patitas"
)
public class TamanioMascota  implements java.io.Serializable {


     private Long idTamanio;
     private String descripcion;
     private char estado;

    public TamanioMascota() {
    }

	
    public TamanioMascota(String descripcion, char estado) {
        this.descripcion = descripcion;
        this.estado = estado;
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_TAMANIO", unique=true, nullable=false)
    public Long getIdTamanio() {
        return this.idTamanio;
    }
    
    public void setIdTamanio(Long idTamanio) {
        this.idTamanio = idTamanio;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="ESTADO", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }




}


