package com.disenio.models.mascotas;
// Generated 29/08/2021 23:04:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoMascota generated by hbm2java
 */
@Entity
@Table(name="tipo_mascota"
    ,catalog="patitas"
)
public class TipoMascota  implements java.io.Serializable {


     private Long idTipoMascota;
     private String nombre;

    public TipoMascota() {
    }

	
    public TipoMascota(String nombre) {
        this.nombre = nombre;
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_TIPO_MASCOTA", unique=true, nullable=false)
    public Long getIdTipoMascota() {
        return this.idTipoMascota;
    }
    
    public void setIdTipoMascota(Long idTipoMascota) {
        this.idTipoMascota = idTipoMascota;
    }

    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }



}


