package com.disenio.models.caracteristicas;
// Generated 29/08/2021 23:04:39 by Hibernate Tools 4.3.1


import com.disenio.models.mascotas.Mascota;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CaracteristicaDetalle generated by hbm2java
 */
@Entity
@Table(name="caracteristica_detalle"
    ,catalog="patitas"
)
public class CaracteristicaDetalle  implements java.io.Serializable {


     private Long idDetalle;
     private CaracteristicaDetalleValor caracteristicaDetalleValor;
     private Mascota mascota;
     private Date fechaAlta;
     private Date fechaUltimaModificacion;
     private Date fechaBaja;
     private char estado;

    public CaracteristicaDetalle() {
    }

	
    public CaracteristicaDetalle(CaracteristicaDetalleValor caracteristicaDetalleValor, Mascota mascota, Date fechaAlta, Date fechaUltimaModificacion, char estado) {
        this.caracteristicaDetalleValor = caracteristicaDetalleValor;
        this.mascota = mascota;
        this.fechaAlta = fechaAlta;
        this.fechaUltimaModificacion = fechaUltimaModificacion;
        this.estado = estado;
    }
    public CaracteristicaDetalle(CaracteristicaDetalleValor caracteristicaDetalleValor, Mascota mascota, Date fechaAlta, Date fechaUltimaModificacion, Date fechaBaja, char estado) {
       this.caracteristicaDetalleValor = caracteristicaDetalleValor;
       this.mascota = mascota;
       this.fechaAlta = fechaAlta;
       this.fechaUltimaModificacion = fechaUltimaModificacion;
       this.fechaBaja = fechaBaja;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_DETALLE", unique=true, nullable=false)
    public Long getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(Long idDetalle) {
        this.idDetalle = idDetalle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CARACTERISTICA", nullable=false)
    public CaracteristicaDetalleValor getCaracteristicaDetalleValor() {
        return this.caracteristicaDetalleValor;
    }
    
    public void setCaracteristicaDetalleValor(CaracteristicaDetalleValor caracteristicaDetalleValor) {
        this.caracteristicaDetalleValor = caracteristicaDetalleValor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_MASCOTA", nullable=false)
    public Mascota getMascota() {
        return this.mascota;
    }
    
    public void setMascota(Mascota mascota) {
        this.mascota = mascota;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ALTA", nullable=false, length=0)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_ULTIMA_MODIFICACION", nullable=false, length=0)
    public Date getFechaUltimaModificacion() {
        return this.fechaUltimaModificacion;
    }
    
    public void setFechaUltimaModificacion(Date fechaUltimaModificacion) {
        this.fechaUltimaModificacion = fechaUltimaModificacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_BAJA", length=0)
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }

    
    @Column(name="ESTADO", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }






}


