package com.disenio.models.caracteristicas;
// Generated 29/08/2021 23:04:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ComportamientoTipo generated by hbm2java
 */
@Entity
@Table(name="comportamiento_tipo"
    ,catalog="patitas"
)
public class ComportamientoTipo  implements java.io.Serializable {


     private Long idComportamientoTipo;
     private String descripcion;

    public ComportamientoTipo() {
    }

	
    public ComportamientoTipo(String descripcion) {
        this.descripcion = descripcion;
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_COMPORTAMIENTO_TIPO", unique=true, nullable=false)
    public Long getIdComportamientoTipo() {
        return this.idComportamientoTipo;
    }
    
    public void setIdComportamientoTipo(Long idComportamientoTipo) {
        this.idComportamientoTipo = idComportamientoTipo;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=20)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }



}


