package com.disenio.model.usuarios;


import com.disenio.model.personas.Persona;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import javax.persistence.*;
import java.util.Calendar;

/**
 * Usuario generated by grupo 10
 */
@Entity
@Data
@Table(name = "usuario", catalog = "patitas")
public class Usuario implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID_USUARIO", unique = true, nullable = false)
    private Integer idUsuario;

    @OneToOne(fetch = FetchType.EAGER,cascade=CascadeType.ALL)
    @JoinColumn(name = "ID_PERSONA")
    private Persona persona;

    @Column(name = "NOMBRE", nullable = false, length = 50)
    private String nombre;

    @Column(name = "CLAVE", nullable = false, length = 80)
    private String clave;

    @Column(name = "FECHA_ALTA", length = 0)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy HH:mm", timezone = "GMT+8")
    private Calendar fechaAlta;


    @Column(name = "FECHA_ULTIMA_MODIFICACION",  length = 0)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy HH:mm", timezone = "GMT+8")
    private Calendar fechaUltimaModificacion;

    @Column(name = "FECHA_BAJA")
    private Integer fechaBaja;

    @Column(name = "CANTIDAD_LOGIN", nullable = false)
    private int cantidadLogin;

    @Column(name = "ESTADO", nullable = false, length = 1)
    private char estado;

    @ManyToOne
    private Rol rol;

    /*
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
    private List<UsuarioOrganizacion> usuarioOrganizacions;
    */

    public Usuario() {
        this.fechaAlta = Calendar.getInstance();
        this.fechaUltimaModificacion = Calendar.getInstance();
        this.estado = 'A';
        this.cantidadLogin = 0;
    }

    public Usuario(Integer idUsuario, Persona persona, String nombre, String clave, Calendar fechaAlta, Calendar fechaUltimaModificacion, Integer fechaBaja, int cantidadLogin, char estado, Rol rol) {
        super();
        this.idUsuario = idUsuario;
        this.persona = persona;
        this.nombre = nombre;
        this.clave = clave;
        this.cantidadLogin = cantidadLogin;
        this.estado = estado;
        this.rol = rol;
    }

    public Usuario(String usuario, String clave, Rol rol) {

        this.nombre = usuario;
        this.clave = clave;
        this.rol = rol;
    }


    public Integer getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    public Persona getPersona() {
        return persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getClave() {
        return clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }

    public Calendar getFechaAlta() {
        return fechaAlta;
    }

    public void setFechaAlta(Calendar fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    public Calendar getFechaUltimaModificacion() {
        return fechaUltimaModificacion;
    }

    public void setFechaUltimaModificacion(Calendar fechaUltimaModificacion) {
        this.fechaUltimaModificacion = fechaUltimaModificacion;
    }

    public Integer getFechaBaja() {
        return fechaBaja;
    }

    public void setFechaBaja(Integer fechaBaja) {
        this.fechaBaja = fechaBaja;
    }

    public int getCantidadLogin() {
        return cantidadLogin;
    }

    public void setCantidadLogin(int cantidadLogin) {
        this.cantidadLogin = cantidadLogin;
    }

    public char getEstado() {
        return estado;
    }

    public void setEstado(char estado) {
        this.estado = estado;
    }

    public Rol getRol() {
        return rol;
    }

    public void setRol(Rol rol) {
        this.rol = rol;
    }
}


