package com.disenio.model.usuarios;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsuarioRol generated by hbm2java
 */
@Entity
@Table(name="usuario_rol",catalog="patitas")
public class UsuarioRol  implements java.io.Serializable {



    private Integer idUsuarioRol;
    private Rol rol;
    private UsuarioOrganizacion usuarioOrganizacion;
    private char estado;

    public UsuarioRol() {
    }

    public UsuarioRol(Rol rol, UsuarioOrganizacion usuarioOrganizacion, char estado) {
        this.rol = rol;
        this.usuarioOrganizacion = usuarioOrganizacion;
        this.estado = estado;
    }

    @Id @GeneratedValue(strategy=IDENTITY)


    @Column(name="ID_USUARIO_ROL", unique=true, nullable=false)
    public Integer getIdUsuarioRol() {
        return this.idUsuarioRol;
    }

    public void setIdUsuarioRol(Integer idUsuarioRol) {
        this.idUsuarioRol = idUsuarioRol;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ROL", nullable=false)
    public Rol getRol() {
        return this.rol;
    }

    public void setRol(Rol rol) {
        this.rol = rol;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USUARIO_ORG", nullable=false)
    public UsuarioOrganizacion getUsuarioOrganizacion() {
        return this.usuarioOrganizacion;
    }

    public void setUsuarioOrganizacion(UsuarioOrganizacion usuarioOrganizacion) {
        this.usuarioOrganizacion = usuarioOrganizacion;
    }


    @Column(name="ESTADO", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }

    public void setEstado(char estado) {
        this.estado = estado;
    }




}


