package com.disenio.model.faq;


import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * generated by grupo10
 */
@Entity
@Data
@Table(name="faq_comportamiento_tipo"
    //,catalog="patitas"
)
public class FaqComportamientoTipo  implements java.io.Serializable {

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="ID_COMPORTAMIENTO_TIPO", unique=true, nullable=false)
     private Integer idComportamientoTipo;

    @Column(name="DESCRIPCION_RESUMIDA", nullable=false, length=50)
     private String descripcionResumida;

    @Column(name="DESCRIPCION", nullable=false, length=2000)
     private String descripcion;

    @JsonIgnore
    @OneToMany(fetch=FetchType.LAZY, mappedBy="faqComportamientoTipo")
     private List<Faq> faqs;


}


