package com.disenio.model.faq;


import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FaqPreguntaTipo generated by grupo 10
 */
@Entity
@Data
@Table(name="faq_pregunta_tipo"
    ,catalog="patitas"
)
public class FaqPreguntaTipo  implements java.io.Serializable {

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="ID_PREGUNTA_TIPO", unique=true, nullable=false)
     private Integer idPreguntaTipo;

    @Column(name="DESCRIPCION_FAQ", nullable=false, length=2000)
     private String descripcionFaq;

    @JsonIgnore
    @OneToMany(fetch=FetchType.LAZY, mappedBy="faqPreguntaTipo")
     private List<Faq> faqs;


}


