package com.disenio.model.faq;


import com.disenio.model.mascotas.CaracteristicaDetalleValor;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FaqRespuestaValor generated by grupo10
 */
@Entity
@Data
@Table(name="faq_respuesta_valor"
    ,catalog="patitas"
)
public class FaqRespuestaValor  implements java.io.Serializable {

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="ID_RESPUESTA_VALOR", unique=true, nullable=false)
     private Integer idRespuestaValor;

    @JsonIgnore
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_FAQ", nullable=false)
     private Faq faq;

    @Column(name="DESCRIPCION", nullable=false, length=2000)
     private String descripcion;

    @JsonIgnore
    @OneToMany(fetch=FetchType.LAZY, mappedBy="faqRespuestaValor")
     private List<CaracteristicaDetalleValor> caracteristicaDetalleValors;



}


