package com.disenio.model.faq;


import com.disenio.model.mascotas.CaracteristicaDetalle;
import lombok.Data;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * FaqRespuestaValor generated by grupo10
 */
@Entity
@Data
@Table(name = "faq_respuesta_valor"
        // , catalog = "patitas"
)
public class FaqRespuestaValor implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID_RESPUESTA_VALOR", unique = true, nullable = false)
    private Integer idRespuestaValor;


    @Column(name = "DESCRIPCION", nullable = false, length = 2000)
    private String descripcion;

}


