package com.disenio.model.personas;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Calendar;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PersonaDireccion generated by grupo10
 */
@Entity
@Table(name = "persona_direccion", catalog = "patitas")
public class PersonaDireccion implements java.io.Serializable {


    private Integer idDireccion;
    private Persona persona;
    private String calle;
    private int numero;
    private Integer piso;
    private String departamento;
    private String observaciones;
    private Integer codPostal;
    private Calendar fechaAlta;
    private Calendar fechaUltimaModificacion;
    private Calendar fechaBaja;
    private char estado;

    public PersonaDireccion() {
    }


    public PersonaDireccion(Persona persona, String calle, int numero, Calendar fechaAlta, Calendar fechaUltimaModificacion, char estado) {
        this.persona = persona;
        this.calle = calle;
        this.numero = numero;
        this.fechaAlta = fechaAlta;
        this.fechaUltimaModificacion = fechaUltimaModificacion;
        this.estado = estado;
    }

    public PersonaDireccion(Persona persona, String calle, int numero, Integer piso, String departamento, String observaciones, Integer codPostal, Calendar fechaAlta, Calendar fechaUltimaModificacion, Calendar fechaBaja, char estado) {
        this.persona = persona;
        this.calle = calle;
        this.numero = numero;
        this.piso = piso;
        this.departamento = departamento;
        this.observaciones = observaciones;
        this.codPostal = codPostal;
        this.fechaAlta = fechaAlta;
        this.fechaUltimaModificacion = fechaUltimaModificacion;
        this.fechaBaja = fechaBaja;
        this.estado = estado;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID_DIRECCION", unique = true, nullable = false)
    public Integer getIdDireccion() {
        return this.idDireccion;
    }

    public void setIdDireccion(Integer idDireccion) {
        this.idDireccion = idDireccion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_PERSONA", nullable = false)
    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }


    @Column(name = "CALLE", nullable = false, length = 200)
    public String getCalle() {
        return this.calle;
    }

    public void setCalle(String calle) {
        this.calle = calle;
    }


    @Column(name = "NUMERO", nullable = false)
    public int getNumero() {
        return this.numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }


    @Column(name = "PISO")
    public Integer getPiso() {
        return this.piso;
    }

    public void setPiso(Integer piso) {
        this.piso = piso;
    }


    @Column(name = "DEPARTAMENTO", length = 2)
    public String getDepartamento() {
        return this.departamento;
    }

    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }


    @Column(name = "OBSERVACIONES", length = 2000)
    public String getObservaciones() {
        return this.observaciones;
    }

    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }


    @Column(name = "COD_POSTAL")
    public Integer getCodPostal() {
        return this.codPostal;
    }

    public void setCodPostal(Integer codPostal) {
        this.codPostal = codPostal;
    }


    @Column(name = "FECHA_ALTA", nullable = false, length = 0)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy HH:mm", timezone = "GMT+8")
    public Calendar getFechaAlta() {
        return this.fechaAlta;
    }

    public void setFechaAlta(Calendar fechaAlta) {
        this.fechaAlta = fechaAlta;
    }


    @Column(name = "FECHA_ULTIMA_MODIFICACION", nullable = false, length = 0)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy HH:mm", timezone = "GMT+8")
    public Calendar getFechaUltimaModificacion() {
        return this.fechaUltimaModificacion;
    }

    public void setFechaUltimaModificacion(Calendar fechaUltimaModificacion) {
        this.fechaUltimaModificacion = fechaUltimaModificacion;
    }


    @Column(name = "FECHA_BAJA", length = 0)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy HH:mm", timezone = "GMT+8")
    public Calendar getFechaBaja() {
        return this.fechaBaja;
    }

    public void setFechaBaja(Calendar fechaBaja) {
        this.fechaBaja = fechaBaja;
    }


    @Column(name = "ESTADO", nullable = false, length = 1)
    public char getEstado() {
        return this.estado;
    }

    public void setEstado(char estado) {
        this.estado = estado;
    }


}


