package com.disenio.model.personas;


import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import javax.persistence.*;
import java.util.Calendar;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * PersonaDocumento generated by grupo 10
 */
@Entity
@Data
@Table(name = "persona_documento"//, catalog = "patitas"
)
public class PersonaDocumento implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID_DOCUMENTO", unique = true, nullable = false)
    private Integer idDocumento;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_TIPO_DOC", nullable = false)
    private TipoDocumento tipoDocumento;

    @Column(name = "NUMERO", nullable = false)
    private int numero;

    @Column(name = "FECHA_ALTA", length = 0)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy HH:mm", timezone = "GMT+8")
    private Calendar fechaAlta;

    @Column(name = "FECHA_ULTIMA_MODIFICACION", length = 0)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy HH:mm", timezone = "GMT+8")
    private Calendar fechaUltimaModificacion;

    @Column(name = "FECHA_BAJA", length = 0)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy HH:mm", timezone = "GMT+8")
    private Calendar fechaBaja;

    @Column(name = "ESTADO", nullable = false, length = 1)
    private char estado;

    public PersonaDocumento() {
        this.estado = 'A';
        this.fechaAlta = Calendar.getInstance();
        this.fechaUltimaModificacion = Calendar.getInstance();
    }
}


