package com.disenio.model.personas;
// Generated 01/09/2021 19:13:39 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoDocumento generated by hbm2java
 */
@Entity
@Table(name="tipo_documento"
    ,catalog="patitas"
)
public class TipoDocumento  implements java.io.Serializable {


     private Integer idTipoDoc;
     private String descripcionCorta;
     private String descripcionLarga;
     private char estado;

    public TipoDocumento() {
    }

	
    public TipoDocumento(String descripcionCorta, String descripcionLarga, char estado) {
        this.descripcionCorta = descripcionCorta;
        this.descripcionLarga = descripcionLarga;
        this.estado = estado;
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_TIPO_DOC", unique=true, nullable=false)
    public Integer getIdTipoDoc() {
        return this.idTipoDoc;
    }
    
    public void setIdTipoDoc(Integer idTipoDoc) {
        this.idTipoDoc = idTipoDoc;
    }

    
    @Column(name="DESCRIPCION_CORTA", nullable=false, length=5)
    public String getDescripcionCorta() {
        return this.descripcionCorta;
    }
    
    public void setDescripcionCorta(String descripcionCorta) {
        this.descripcionCorta = descripcionCorta;
    }

    
    @Column(name="DESCRIPCION_LARGA", nullable=false, length=50)
    public String getDescripcionLarga() {
        return this.descripcionLarga;
    }
    
    public void setDescripcionLarga(String descripcionLarga) {
        this.descripcionLarga = descripcionLarga;
    }

    
    @Column(name="ESTADO", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }



}


